#### AWS variables ####
aws_secret_key = "****"
aws_access_key = "****"
aws_region = "us-west-2"
creation_token = "myproduct"
provision_aws_resource = "false"
##### Azure Variables ####
azure_client_id = "****"
azure_client_secret = "****"
azure_tenant_id = "****"
azure_subscription_id = "****"
provision_azure_resource = "true"
share_name = "myfileshare"
rg_name = "myrg"
location = "northcentralus" 