#### AWS variables ####
aws_secret_key = "****"
aws_access_key = "****"
aws_region ="us-west-2"
aws_vm_name = "myvm"
aws_vm_type = "t2.micro"
aws_vm_image = "ami-005e54dee72cc1d00"
provision_aws_resource = "true"
##### Azure Variables ########
azure_client_id = "****"
azure_client_secret = "****"
azure_tenant_id = "****"
azure_subscription_id = "****"
provision_azure_resource = "true"
azure_vm_name = "myvmazure"
azure_vm_type = "Standard_DS1_v2"